---
- hosts: docker
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: grab GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
    - name: add user "{{ansible_user}}" to docker group
      user:
        name: "{{ansible_user}}"
        groups: docker
        append: yes
    - name: make sure docker is active
      service:
        name: docker
        state: started
        enabled: yes
  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted