---
# Create workspace by cloning docker repository and start docker-compose
# Can be improved by using docker-compose module
- hosts: docker
  tasks:
    - name: Clone opennms docker automation repo
      git:
            repo: https://github.com/jb68/nmsdops.git
            version: master
            dest: "{{ ws_path }}/nmsdops"
            clone: yes
            update: yes
      notify:
              - docker compose down
              - docker compose up

    - name: Register real path for repo to be used with root
      command: pwd chdir="{{ ws_path }}//nmsdops"
      register: repo_path
    - debug:
        var: repo_path.stdout

      # horizon docker user needs write permission on folders (chmod 777 or chown 10001)
    - name: Set folder owner to 10001
      file: path="{{ repo_path.stdout }}/docker/horizon/{{ item }}" owner=10001
      with_items:
        - conf.etc
        - conf.overlay
        - data
      become: yes

    # - name: FirewallD rules
    #   firewalld:
    #     permanent: yes
    #     immediate: yes
    #     port: "{{ item }}"
    #     state: enabled
    #   with_items:
    #    - 8980/tcp

  handlers:
    - name: docker compose down
      shell:
        cmd: "docker-compose -f docker-compose.yml down"
        chdir: "{{ repo_path.stdout }}/docker"
    - name: docker compose up
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: "{{ repo_path.stdout }}/docker"

    - name: restart postgres
      shell:
        cmd: "docker-compose -f docker-compose.yml restart postgres -d"
        chdir: "{{ repo_path.stdout }}/docker"
      listen: restart cluster

    - name: restart horizon
      shell:
        cmd: "docker-compose -f docker-compose.yml restart horizon -d"
        chdir: "{{ repo_path.stdout }}/docker"
      listen: restart cluster
